export const CREDIT_ADDED_SUCCESS = 'CREDIT_ADDED_SUCCESS';
export const CREDIT_ADDED_FAIL = 'CREDIT_ADDED_FAIL';
export const CREDITS_FETCH_SUCCESS = "CREDITS_FETCH_SUCCESS";
export const CREDIT_FETCH_SUCCESS = "CREDIT_FETCH_SUCCESS";
export const CREDIT_CHANGED = "CREDIT_CHANGED";
export const CREDIT_DELETED = "CREDIT_DELETED";
export const CREDIT_ACTION_SUCCESS="CREDIT_ACTION_SUCCESS";
export const FINISH_CREDIT_ACTION="FINISH_CREDIT_ACTION";


export const USER_DELETED = "USER_DELETED"
export const USER_ADDED_SUCCESS = 'USER_ADDED_SUCCESS';
export const USER_ADDED_FAIL = 'USER_ADDED_FAIL';
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USERS_FETCH_SUCCESS = "USERS_FETCH_SUCCESS";
export const USER_CHANGED = "USER_CHANGED";
export const USER_ACTION_SUCCESS="USER_ACTION_SUCCESS";
export const FINISH_USER_ACTION="FINISH_USER_ACTION";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"

export const CONTRACT_ADDED_SUCCESS = 'CONTRACT_ADDED_SUCCESS';
export const CONTRACT_ADDED_FAIL = 'CONTRACT_ADDED_FAIL';
export const CONTRACTS_FETCH_SUCCESS = "CONTRACTS_FETCH_SUCCESS";
export const CONTRACT_FETCH_SUCCESS = "CONTRACT_FETCH_SUCCESS";
export const CONTRACT_CHANGED = "CONTRACT_CHANGED";
export const CONTRACT_DELETED = "CONTRACT_DELETED";
export const CONTRACT_ACTION_SUCCESS="CONTRACT_ACTION_SUCCESS";
export const FINISH_CONTRACT_ACTION="FINISH_CONTRACT_ACTION";
